ALTER TABLE characters MODIFY COLUMN equipslots INT(11) NOT NULL DEFAULT '96';
ALTER TABLE characters MODIFY COLUMN useslots INT(11) NOT NULL DEFAULT '96';
ALTER TABLE characters MODIFY COLUMN setupslots INT(11) NOT NULL DEFAULT '96';
ALTER TABLE characters MODIFY COLUMN etcslots INT(11) NOT NULL DEFAULT '96';
